# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations

def create_document_types(apps, schema_editor):
    """Create basic document types for the expropriation process."""
    DocumentType = apps.get_model('documents', 'DocumentType')
    Department = apps.get_model('core', 'Department')

    # Get departments for assignment
    dept_mapping = {}
    for dept in Department.objects.all():
        dept_mapping[dept.code] = dept

    document_types = [
        # Initial Request Documents
        {
            'name': 'Solicitud de Expropiación',
            'code': 'SOL_EXP',
            'description': 'Formulario oficial de solicitud de expropiación',
            'is_required': True,
            'department': dept_mapping.get('DS'),
            'allowed_formats': 'PDF,DOC,DOCX',
            'max_size_mb': 10,
            'order': 1,
        },
        {
            'name': 'Cédula del Propietario',
            'code': 'CED_PROP',
            'description': 'Copia de cédula del propietario del inmueble',
            'is_required': True,
            'department': dept_mapping.get('DS'),
            'allowed_formats': 'PDF,JPG,JPEG,PNG',
            'max_size_mb': 5,
            'order': 2,
        },
        {
            'name': 'Título de Propiedad',
            'code': 'TIT_PROP',
            'description': 'Título de propiedad del inmueble',
            'is_required': True,
            'department': dept_mapping.get('DS'),
            'allowed_formats': 'PDF,DOC,DOCX',
            'max_size_mb': 15,
            'order': 3,
        },
        {
            'name': 'Certificado de Gravamen',
            'code': 'CERT_GRAV',
            'description': 'Certificado de gravamen del inmueble',
            'is_required': True,
            'department': dept_mapping.get('DS'),
            'allowed_formats': 'PDF',
            'max_size_mb': 5,
            'order': 4,
        },

        # Legal Documents
        {
            'name': 'Dictamen Legal',
            'code': 'DICT_LEG',
            'description': 'Dictamen del departamento jurídico',
            'is_required': True,
            'department': dept_mapping.get('DJ'),
            'allowed_formats': 'PDF,DOC,DOCX',
            'max_size_mb': 10,
            'order': 5,
        },
        {
            'name': 'Resolución Administrativa',
            'code': 'RES_ADM',
            'description': 'Resolución administrativa inicial',
            'is_required': True,
            'department': dept_mapping.get('DJ'),
            'allowed_formats': 'PDF',
            'max_size_mb': 8,
            'order': 6,
        },

        # Technical Documents
        {
            'name': 'Informe Técnico',
            'code': 'INF_TEC',
            'description': 'Informe técnico del predio',
            'is_required': True,
            'department': dept_mapping.get('DT'),
            'allowed_formats': 'PDF,DOC,DOCX',
            'max_size_mb': 20,
            'order': 7,
        },
        {
            'name': 'Planos del Predio',
            'code': 'PLAN_PRED',
            'description': 'Planos topográficos y arquitectónicos',
            'is_required': True,
            'department': dept_mapping.get('DT'),
            'allowed_formats': 'PDF,DWG,DXF',
            'max_size_mb': 25,
            'order': 8,
        },
        {
            'name': 'Memoria Descriptiva',
            'code': 'MEM_DESC',
            'description': 'Memoria descriptiva del inmueble',
            'is_required': True,
            'department': dept_mapping.get('DT'),
            'allowed_formats': 'PDF,DOC,DOCX',
            'max_size_mb': 10,
            'order': 9,
        },

        # Valuation Documents
        {
            'name': 'Avalúo Comercial',
            'code': 'AVAL_COM',
            'description': 'Avalúo comercial del inmueble',
            'is_required': True,
            'department': dept_mapping.get('DA'),
            'allowed_formats': 'PDF,DOC,DOCX',
            'max_size_mb': 15,
            'order': 10,
        },
        {
            'name': 'Avalúo Catastral',
            'code': 'AVAL_CAT',
            'description': 'Avalúo catastral del inmueble',
            'is_required': True,
            'department': dept_mapping.get('DA'),
            'allowed_formats': 'PDF',
            'max_size_mb': 10,
            'order': 11,
        },

        # Environmental Documents
        {
            'name': 'Estudio de Impacto Ambiental',
            'code': 'EST_IMP_AMB',
            'description': 'Estudio de impacto ambiental del proyecto',
            'is_required': True,
            'department': dept_mapping.get('DAMB'),
            'allowed_formats': 'PDF,DOC,DOCX',
            'max_size_mb': 30,
            'order': 12,
        },
        {
            'name': 'Permiso Ambiental',
            'code': 'PERM_AMB',
            'description': 'Permiso ambiental correspondiente',
            'is_required': True,
            'department': dept_mapping.get('DAMB'),
            'allowed_formats': 'PDF',
            'max_size_mb': 8,
            'order': 13,
        },

        # Urban Planning Documents
        {
            'name': 'Certificado de Uso de Suelo',
            'code': 'CERT_USO_SUELO',
            'description': 'Certificado de uso de suelo del predio',
            'is_required': True,
            'department': dept_mapping.get('DPU'),
            'allowed_formats': 'PDF',
            'max_size_mb': 5,
            'order': 14,
        },
        {
            'name': 'Zonificación Urbana',
            'code': 'ZON_URB',
            'description': 'Documento de zonificación urbana',
            'is_required': True,
            'department': dept_mapping.get('DPU'),
            'allowed_formats': 'PDF,DOC,DOCX',
            'max_size_mb': 10,
            'order': 15,
        },

        # Financial Documents
        {
            'name': 'Estudio de Viabilidad Financiera',
            'code': 'EST_VIAB_FIN',
            'description': 'Estudio de viabilidad financiera del proyecto',
            'is_required': True,
            'department': dept_mapping.get('DF'),
            'allowed_formats': 'PDF,XLS,XLSX',
            'max_size_mb': 15,
            'order': 16,
        },
        {
            'name': 'Presupuesto Aprobado',
            'code': 'PRES_APROB',
            'description': 'Presupuesto aprobado para la expropiación',
            'is_required': True,
            'department': dept_mapping.get('DF'),
            'allowed_formats': 'PDF,XLS,XLSX',
            'max_size_mb': 10,
            'order': 17,
        },

        # Social Impact Documents
        {
            'name': 'Estudio de Impacto Social',
            'code': 'EST_IMP_SOC',
            'description': 'Estudio de impacto social en la comunidad',
            'is_required': True,
            'department': dept_mapping.get('DDS'),
            'allowed_formats': 'PDF,DOC,DOCX',
            'max_size_mb': 20,
            'order': 18,
        },
        {
            'name': 'Plan de Relocalización',
            'code': 'PLAN_RELOC',
            'description': 'Plan de relocalización de afectados',
            'is_required': True,
            'department': dept_mapping.get('DDS'),
            'allowed_formats': 'PDF,DOC,DOCX',
            'max_size_mb': 15,
            'order': 19,
        },

        # Notification Documents
        {
            'name': 'Notificación Publicada',
            'code': 'NOT_PUB',
            'description': 'Comprobante de notificación publicada en periódico',
            'is_required': True,
            'department': dept_mapping.get('DNOT'),
            'allowed_formats': 'PDF,JPG,JPEG,PNG',
            'max_size_mb': 5,
            'order': 20,
        },
        {
            'name': 'Notificación Personal',
            'code': 'NOT_PERS',
            'description': 'Comprobante de notificación personal al propietario',
            'is_required': True,
            'department': dept_mapping.get('DNOT'),
            'allowed_formats': 'PDF,JPG,JPEG,PNG',
            'max_size_mb': 5,
            'order': 21,
        },

        # Negotiation Documents
        {
            'name': 'Oferta de Compra',
            'code': 'OFERTA_COMPRA',
            'description': 'Oferta formal de compra al propietario',
            'is_required': True,
            'department': dept_mapping.get('DNEG'),
            'allowed_formats': 'PDF,DOC,DOCX',
            'max_size_mb': 8,
            'order': 22,
        },
        {
            'name': 'Acta de Negociación',
            'code': 'ACTA_NEG',
            'description': 'Acta de reunión de negociación',
            'is_required': True,
            'department': dept_mapping.get('DNEG'),
            'allowed_formats': 'PDF,DOC,DOCX',
            'max_size_mb': 10,
            'order': 23,
        },
        {
            'name': 'Contrato de Compraventa',
            'code': 'CONT_COMPRAV',
            'description': 'Contrato de compraventa firmado',
            'is_required': True,
            'department': dept_mapping.get('DNEG'),
            'allowed_formats': 'PDF',
            'max_size_mb': 15,
            'order': 24,
        },

        # Payment Documents
        {
            'name': 'Comprobante de Pago',
            'code': 'COMP_PAGO',
            'description': 'Comprobante de pago al propietario',
            'is_required': True,
            'department': dept_mapping.get('DPAG'),
            'allowed_formats': 'PDF,JPG,JPEG,PNG',
            'max_size_mb': 5,
            'order': 25,
        },
        {
            'name': 'Orden de Pago',
            'code': 'ORD_PAGO',
            'description': 'Orden de pago emitida',
            'is_required': True,
            'department': dept_mapping.get('DPAG'),
            'allowed_formats': 'PDF',
            'max_size_mb': 5,
            'order': 26,
        },

        # Registration Documents
        {
            'name': 'Escritura de Transferencia',
            'code': 'ESC_TRANS',
            'description': 'Escritura pública de transferencia de dominio',
            'is_required': True,
            'department': dept_mapping.get('DREG'),
            'allowed_formats': 'PDF',
            'max_size_mb': 15,
            'order': 27,
        },
        {
            'name': 'Certificado de Registro',
            'code': 'CERT_REG',
            'description': 'Certificado de registro de la transferencia',
            'is_required': True,
            'department': dept_mapping.get('DREG'),
            'allowed_formats': 'PDF',
            'max_size_mb': 5,
            'order': 28,
        },

        # Supporting Documents
        {
            'name': 'Fotografías del Predio',
            'code': 'FOT_PRED',
            'description': 'Fotografías actuales del predio',
            'is_required': False,
            'department': dept_mapping.get('DT'),
            'allowed_formats': 'JPG,JPEG,PNG',
            'max_size_mb': 20,
            'order': 29,
        },
        {
            'name': 'Facturas de Servicios',
            'code': 'FACT_SERV',
            'description': 'Facturas de servicios públicos del predio',
            'is_required': False,
            'department': dept_mapping.get('DS'),
            'allowed_formats': 'PDF,JPG,JPEG,PNG',
            'max_size_mb': 10,
            'order': 30,
        },
    ]

    for doc_type_data in document_types:
        # Remove department reference if None
        if doc_type_data['department'] is None:
            del doc_type_data['department']
        DocumentType.objects.create(**doc_type_data)

def reverse_document_types(apps, schema_editor):
    """Reverse the creation of document types."""
    DocumentType = apps.get_model('documents', 'DocumentType')
    DocumentType.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('core', '0002_create_initial_departments'),
    ]

    operations = [
        migrations.RunPython(create_document_types, reverse_document_types),
    ]