# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations

def create_default_permissions(apps, schema_editor):
    """Create default permissions for the RBAC system."""
    Permission = apps.get_model('core', 'Permission')

    permissions = [
        # User Management Permissions
        {
            'name': 'Crear Usuarios',
            'description': 'Permite crear nuevos usuarios en el sistema',
            'resource': 'usuario',
            'action': 'crear',
        },
        {
            'name': 'Ver Usuarios',
            'description': 'Permite ver información de usuarios',
            'resource': 'usuario',
            'action': 'leer',
        },
        {
            'name': 'Actualizar Usuarios',
            'description': 'Permite modificar información de usuarios',
            'resource': 'usuario',
            'action': 'actualizar',
        },
        {
            'name': 'Eliminar Usuarios',
            'description': 'Permite eliminar usuarios del sistema',
            'resource': 'usuario',
            'action': 'eliminar',
        },

        # Expediente Management Permissions
        {
            'name': 'Crear Expedientes',
            'description': 'Permite crear nuevos expedientes de expropiación',
            'resource': 'expediente',
            'action': 'crear',
        },
        {
            'name': 'Ver Expedientes',
            'description': 'Permite ver información de expedientes',
            'resource': 'expediente',
            'action': 'leer',
        },
        {
            'name': 'Actualizar Expedientes',
            'description': 'Permite modificar información de expedientes',
            'resource': 'expediente',
            'action': 'actualizar',
        },
        {
            'name': 'Eliminar Expedientes',
            'description': 'Permite eliminar expedientes',
            'resource': 'expediente',
            'action': 'eliminar',
        },
        {
            'name': 'Aprobar Expedientes',
            'description': 'Permite aprobar expedientes en el workflow',
            'resource': 'expediente',
            'action': 'aprobar',
        },
        {
            'name': 'Rechazar Expedientes',
            'description': 'Permite rechazar expedientes en el workflow',
            'resource': 'expediente',
            'action': 'rechazar',
        },

        # Document Management Permissions
        {
            'name': 'Crear Documentos',
            'description': 'Permite subir y crear nuevos documentos',
            'resource': 'documento',
            'action': 'crear',
        },
        {
            'name': 'Ver Documentos',
            'description': 'Permite ver y descargar documentos',
            'resource': 'documento',
            'action': 'leer',
        },
        {
            'name': 'Actualizar Documentos',
            'description': 'Permite modificar información de documentos',
            'resource': 'documento',
            'action': 'actualizar',
        },
        {
            'name': 'Eliminar Documentos',
            'description': 'Permite eliminar documentos',
            'resource': 'documento',
            'action': 'eliminar',
        },
        {
            'name': 'Aprobar Documentos',
            'description': 'Permite aprobar documentos en revisión',
            'resource': 'documento',
            'action': 'aprobar',
        },
        {
            'name': 'Rechazar Documentos',
            'description': 'Permite rechazar documentos en revisión',
            'resource': 'documento',
            'action': 'rechazar',
        },

        # Task Management Permissions
        {
            'name': 'Crear Tareas',
            'description': 'Permite crear nuevas tareas',
            'resource': 'tarea',
            'action': 'crear',
        },
        {
            'name': 'Ver Tareas',
            'description': 'Permite ver información de tareas',
            'resource': 'tarea',
            'action': 'leer',
        },
        {
            'name': 'Actualizar Tareas',
            'description': 'Permite modificar información de tareas',
            'resource': 'tarea',
            'action': 'actualizar',
        },
        {
            'name': 'Eliminar Tareas',
            'description': 'Permite eliminar tareas',
            'resource': 'tarea',
            'action': 'eliminar',
        },
        {
            'name': 'Asignar Tareas',
            'description': 'Permite asignar tareas a usuarios',
            'resource': 'tarea',
            'action': 'asignar',
        },
        {
            'name': 'Completar Tareas',
            'description': 'Permite marcar tareas como completadas',
            'resource': 'tarea',
            'action': 'completar',
        },

        # Department Management Permissions
        {
            'name': 'Crear Departamentos',
            'description': 'Permite crear nuevos departamentos',
            'resource': 'departamento',
            'action': 'crear',
        },
        {
            'name': 'Ver Departamentos',
            'description': 'Permite ver información de departamentos',
            'resource': 'departamento',
            'action': 'leer',
        },
        {
            'name': 'Actualizar Departamentos',
            'description': 'Permite modificar información de departamentos',
            'resource': 'departamento',
            'action': 'actualizar',
        },
        {
            'name': 'Eliminar Departamentos',
            'description': 'Permite eliminar departamentos',
            'resource': 'departamento',
            'action': 'eliminar',
        },

        # Report Permissions
        {
            'name': 'Ver Reportes',
            'description': 'Permite acceder a reportes del sistema',
            'resource': 'reporte',
            'action': 'leer',
        },
        {
            'name': 'Generar Reportes',
            'description': 'Permite generar nuevos reportes',
            'resource': 'reporte',
            'action': 'crear',
        },
        {
            'name': 'Exportar Reportes',
            'description': 'Permite exportar reportes',
            'resource': 'reporte',
            'action': 'exportar',
        },

        # System Administration Permissions
        {
            'name': 'Administrar Sistema',
            'description': 'Permite acceso completo a administración del sistema',
            'resource': 'sistema',
            'action': 'administrar',
        },
        {
            'name': 'Ver Auditoría',
            'description': 'Permite ver logs de auditoría del sistema',
            'resource': 'auditoria',
            'action': 'leer',
        },
        {
            'name': 'Configurar Sistema',
            'description': 'Permite configurar parámetros del sistema',
            'resource': 'configuracion',
            'action': 'configurar',
        },

        # Workflow Management Permissions
        {
            'name': 'Gestionar Workflow',
            'description': 'Permite gestionar estados y transiciones del workflow',
            'resource': 'workflow',
            'action': 'gestionar',
        },
        {
            'name': 'Transicionar Expedientes',
            'description': 'Permite mover expedientes entre estados del workflow',
            'resource': 'workflow',
            'action': 'transicionar',
        },

        # Notification Permissions
        {
            'name': 'Enviar Notificaciones',
            'description': 'Permite enviar notificaciones a usuarios',
            'resource': 'notificacion',
            'action': 'enviar',
        },
        {
            'name': 'Ver Notificaciones',
            'description': 'Permite ver notificaciones del sistema',
            'resource': 'notificacion',
            'action': 'leer',
        },
    ]

    for perm_data in permissions:
        Permission.objects.create(**perm_data)

def reverse_default_permissions(apps, schema_editor):
    """Reverse the creation of default permissions."""
    Permission = apps.get_model('core', 'Permission')
    Permission.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_initial_departments'),
    ]

    operations = [
        migrations.RunPython(create_default_permissions, reverse_default_permissions),
    ]